name: CI/CD

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '*.md'
      - 'LICENSE'
      - '.github/workflows/*.yml'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '*.md'
      - 'LICENSE'
      - '.github/workflows/*.yml'

jobs:
  check:
    name: Lint & Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v22

      - name: Run ShellCheck
        run: nix develop --command shellcheck src/dsb.sh

      - name: Build DSB Package
        run: nix build .#default
